[wokwi]
version = 1
# Switch firmware path between lab5 and lab6:
# Lab 5: .pio/build/mega_lab5/firmware.hex  (elf: .pio/build/mega_lab5/firmware.elf)
firmware = '../../.pio/build/mega_lab5/firmware.hex'
elf = '../../.pio/build/mega_lab5/firmware.elf'
